### ISSUE TITLE
Can delete the  Image suffix and you should put all the train/test/val images together

### ISSUE THREAD

**Issue by Mr-ind1fferent** [aweihao/ExDark2Yolo#1]

**Comment by Mr-ind1fferent** [comment]
just like Train/images/xxxx.jpg
                     /labels/xxxx.txt

**Comment by Mr-ind1fferent** [comment]
Just like
```
Train/images/xxxx.jpg
        /labels/xxxx.txt
 Test/images/xxxx.jpg
       /labels/xxxx.txt
```

**Comment by wraphex** [comment]
The change has been committed to the repository: https://github.com/aweihao/ExDark2Yolo/commit/8634febff756464239e200f6d0414bb2d7f3907a | https://github.com/aweihao/ExDark2Yolo/commit/ac794de8615b9dcdbab892d115219ac46f4b31f3
